
name: github action session

on:
  workflow_dispatch:
      inputs:
            logLevel:
              description: 'Log level'
              required: true
              default: 'warning'
              type: choice
              options:
              - info
              - warning
              - debug
            tags:
              description: 'Test scenario tags'
              required: false
              type: boolean
            message:
              description: 'Pass on some string stuff'
              required: false


jobs:
  base-flow-jobs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        env:
            MESSAGE: ${{ inputs.message }}   
        run: "echo Here is what i got from UI $MESSAGE"

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
