
name: github action session - rest api base invocation

on: 
  repository_dispatch:
    types: [build]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Check payload
        run: |
          echo "${{github.event.client_payload.name}}"
          echo "${{github.event.client_payload.lastName}}"
      - name: javascript base actions
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Consumer'
      - name: display output from javascript based actions
        run: echo "${{ steps.greet.outputs.time }}"
