
name: github action session - rest api base invocation

on: 
  repository_dispatch:
    types: [build]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Check payload
        run: |
          echo "${{github.event.client_payload.name}}"
          echo "${{github.event.client_payload.lastName}}"
      - name: javascript base actions
        id: greet
        env: 
          WHO_TO_GREET: ${{github.event.client_payload.name}}
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: $WHO_TO_GREET
      - name: display output from javascript based actions
        run: echo "Hello ${{github.event.client_payload.name}} --> Time is ${{ steps.greet.outputs.time }}"
      - name: utilize secrets
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: echo "Here is the secrets $DISCORD_WEBHOOK"
