
name: github action session

on: 
  repository_dispatch:
    types: [build]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Check payload
        run: |
          echo "${{github.event.client_payload.name}}"
          echo "${{github.event.client_payload.lastName}}"


